name: Auth App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.14.0'

    - name: Install dependencies
      run: npm install 

    - name: Run build
      run: npm run build 

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: dist

    - name: Deploy to Vercel
      if: github.ref == 'refs/heads/main' 
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      run: |
        curl -sL https://github.com/vercel/vercel/releases/download/v29.0.0/vercel-linux-amd64.tar.gz | tar -xz
        ./vercel --token $VERCEL_TOKEN --confirm --prod

